"""add anonymous reads and emails tables

Revision ID: 92fb86435125
Revises: b8e0e07f9645
Create Date: 2026-06-04 07:51:52.464688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92fb86435125'
down_revision: Union[str, Sequence[str], None] = 'b8e0e07f9645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('fingerprint_id', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_emails_email'), 'anonymous_emails', ['email'], unique=False)
    op.create_index(op.f('ix_anonymous_emails_fingerprint_id'), 'anonymous_emails', ['fingerprint_id'], unique=False)
    op.create_index(op.f('ix_anonymous_emails_id'), 'anonymous_emails', ['id'], unique=False)
    op.create_table('anonymous_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_reads_fingerprint_id'), 'anonymous_reads', ['fingerprint_id'], unique=False)
    op.create_index(op.f('ix_anonymous_reads_id'), 'anonymous_reads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anonymous_reads_id'), table_name='anonymous_reads')
    op.drop_index(op.f('ix_anonymous_reads_fingerprint_id'), table_name='anonymous_reads')
    op.drop_table('anonymous_reads')
    op.drop_index(op.f('ix_anonymous_emails_id'), table_name='anonymous_emails')
    op.drop_index(op.f('ix_anonymous_emails_fingerprint_id'), table_name='anonymous_emails')
    op.drop_index(op.f('ix_anonymous_emails_email'), table_name='anonymous_emails')
    op.drop_table('anonymous_emails')
    # ### end Alembic commands ###
