"""add mpesa fields to transactions

Revision ID: 96b3a9d50eb1
Revises: d85b0fda8b4f
Create Date: 2026-06-01 04:20:49.493884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b3a9d50eb1'
down_revision: Union[str, Sequence[str], None] = 'd85b0fda8b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
