"""add free article reads table

Revision ID: b8e0e07f9645
Revises: 83c0ff49ee39
Create Date: 2026-06-04 06:16:17.187100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e0e07f9645'
down_revision: Union[str, Sequence[str], None] = '83c0ff49ee39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('free_article_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_free_article_reads_id'), 'free_article_reads', ['id'], unique=False)
    op.create_index(op.f('ix_free_article_reads_user_id'), 'free_article_reads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_free_article_reads_user_id'), table_name='free_article_reads')
    op.drop_index(op.f('ix_free_article_reads_id'), table_name='free_article_reads')
    op.drop_table('free_article_reads')
    # ### end Alembic commands ###
